import type {
  CableType,
  InstallationType,
  NumberOfPhases,
} from "../types/types";

interface ValuesTable {
  cableName: CableType;
  multi: {
    installationType: InstallationType;
    numberOfPhases: NumberOfPhases;
    veinCrossing: string;
    liczbaZyli: string | number;
    liczbaZyliObciazonychPradowo: number;
    numbers: {
      loadCurrent: number | null;
      crossSectionOfVein: string;
    }[];
  }[];
  one?: {
    installationType: InstallationType;
    numberOfPhases: NumberOfPhases;
    veinCrossing: string;
    liczbaZyli: string | number;
    liczbaZyliObciazonychPradowo: number;
    numbers: {
      loadCurrent: number | null;
      crossSectionOfVein: string;
    }[];
  }[];
}

export const values: ValuesTable[] = [
  {
    cableName: "YDY",
    multi: [
      {
        installationType: "A1",
        numberOfPhases: 1,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: 3,
        liczbaZyliObciazonychPradowo: 2,
        numbers: [
          { loadCurrent: 14.5, crossSectionOfVein: "1,5" },
          { loadCurrent: 19.5, crossSectionOfVein: "2,5" },
          { loadCurrent: 26, crossSectionOfVein: "4" },
          { loadCurrent: 34, crossSectionOfVein: "6" },
          { loadCurrent: 46, crossSectionOfVein: "10" },
          { loadCurrent: 61, crossSectionOfVein: "16" },
          { loadCurrent: 80, crossSectionOfVein: "25" },
          { loadCurrent: 99, crossSectionOfVein: "35" },
          { loadCurrent: 119, crossSectionOfVein: "50" },
          { loadCurrent: 151, crossSectionOfVein: "70" },
          { loadCurrent: 182, crossSectionOfVein: "95" },
          { loadCurrent: 210, crossSectionOfVein: "120" },
          { loadCurrent: 240, crossSectionOfVein: "150" },
          { loadCurrent: 273, crossSectionOfVein: "185" },
          { loadCurrent: 321, crossSectionOfVein: "240" },
          { loadCurrent: 367, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "A1",
        numberOfPhases: 3,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: "4 lub 5",
        liczbaZyliObciazonychPradowo: 3,
        numbers: [
          { loadCurrent: 13.5, crossSectionOfVein: "1,5" },
          { loadCurrent: 18, crossSectionOfVein: "2,5" },
          { loadCurrent: 24, crossSectionOfVein: "4" },
          { loadCurrent: 31, crossSectionOfVein: "6" },
          { loadCurrent: 42, crossSectionOfVein: "10" },
          { loadCurrent: 56, crossSectionOfVein: "16" },
          { loadCurrent: 73, crossSectionOfVein: "25" },
          { loadCurrent: 89, crossSectionOfVein: "35" },
          { loadCurrent: 108, crossSectionOfVein: "50" },
          { loadCurrent: 136, crossSectionOfVein: "70" },
          { loadCurrent: 164, crossSectionOfVein: "95" },
          { loadCurrent: 188, crossSectionOfVein: "120" },
          { loadCurrent: 216, crossSectionOfVein: "150" },
          { loadCurrent: 245, crossSectionOfVein: "185" },
          { loadCurrent: 286, crossSectionOfVein: "240" },
          { loadCurrent: 328, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "A2",
        numberOfPhases: 1,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: 3,
        liczbaZyliObciazonychPradowo: 2,
        numbers: [
          { loadCurrent: 14, crossSectionOfVein: "1,5" },
          { loadCurrent: 18.5, crossSectionOfVein: "2,5" },
          { loadCurrent: 25, crossSectionOfVein: "4" },
          { loadCurrent: 32, crossSectionOfVein: "6" },
          { loadCurrent: 43, crossSectionOfVein: "10" },
          { loadCurrent: 57, crossSectionOfVein: "16" },
          { loadCurrent: 75, crossSectionOfVein: "25" },
          { loadCurrent: 92, crossSectionOfVein: "35" },
          { loadCurrent: 110, crossSectionOfVein: "50" },
          { loadCurrent: 139, crossSectionOfVein: "70" },
          { loadCurrent: 167, crossSectionOfVein: "95" },
          { loadCurrent: 192, crossSectionOfVein: "120" },
          { loadCurrent: 219, crossSectionOfVein: "150" },
          { loadCurrent: 248, crossSectionOfVein: "185" },
          { loadCurrent: 291, crossSectionOfVein: "240" },
          { loadCurrent: 334, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "A2",
        numberOfPhases: 3,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: "4 lub 5",
        liczbaZyliObciazonychPradowo: 3,
        numbers: [
          { loadCurrent: 13, crossSectionOfVein: "1,5" },
          { loadCurrent: 17.5, crossSectionOfVein: "2,5" },
          { loadCurrent: 23, crossSectionOfVein: "4" },
          { loadCurrent: 29, crossSectionOfVein: "6" },
          { loadCurrent: 39, crossSectionOfVein: "10" },
          { loadCurrent: 52, crossSectionOfVein: "16" },
          { loadCurrent: 68, crossSectionOfVein: "25" },
          { loadCurrent: 83, crossSectionOfVein: "35" },
          { loadCurrent: 99, crossSectionOfVein: "50" },
          { loadCurrent: 125, crossSectionOfVein: "70" },
          { loadCurrent: 150, crossSectionOfVein: "95" },
          { loadCurrent: 172, crossSectionOfVein: "120" },
          { loadCurrent: 196, crossSectionOfVein: "150" },
          { loadCurrent: 223, crossSectionOfVein: "185" },
          { loadCurrent: 261, crossSectionOfVein: "240" },
          { loadCurrent: 298, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "B2",
        numberOfPhases: 1,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: 3,
        liczbaZyliObciazonychPradowo: 2,
        numbers: [
          { loadCurrent: 16.5, crossSectionOfVein: "1,5" },
          { loadCurrent: 23, crossSectionOfVein: "2,5" },
          { loadCurrent: 30, crossSectionOfVein: "4" },
          { loadCurrent: 38, crossSectionOfVein: "6" },
          { loadCurrent: 52, crossSectionOfVein: "10" },
          { loadCurrent: 69, crossSectionOfVein: "16" },
          { loadCurrent: 90, crossSectionOfVein: "25" },
          { loadCurrent: 111, crossSectionOfVein: "35" },
          { loadCurrent: 133, crossSectionOfVein: "50" },
          { loadCurrent: 168, crossSectionOfVein: "70" },
          { loadCurrent: 201, crossSectionOfVein: "95" },
          { loadCurrent: 232, crossSectionOfVein: "120" },
          { loadCurrent: 258, crossSectionOfVein: "150" },
          { loadCurrent: 294, crossSectionOfVein: "185" },
          { loadCurrent: 344, crossSectionOfVein: "240" },
          { loadCurrent: 394, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "B2",
        numberOfPhases: 3,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: "4 lub 5",
        liczbaZyliObciazonychPradowo: 3,
        numbers: [
          { loadCurrent: 15, crossSectionOfVein: "1,5" },
          { loadCurrent: 20, crossSectionOfVein: "2,5" },
          { loadCurrent: 27, crossSectionOfVein: "4" },
          { loadCurrent: 34, crossSectionOfVein: "6" },
          { loadCurrent: 46, crossSectionOfVein: "10" },
          { loadCurrent: 62, crossSectionOfVein: "16" },
          { loadCurrent: 80, crossSectionOfVein: "25" },
          { loadCurrent: 99, crossSectionOfVein: "35" },
          { loadCurrent: 118, crossSectionOfVein: "50" },
          { loadCurrent: 149, crossSectionOfVein: "70" },
          { loadCurrent: 179, crossSectionOfVein: "95" },
          { loadCurrent: 206, crossSectionOfVein: "120" },
          { loadCurrent: 225, crossSectionOfVein: "150" },
          { loadCurrent: 255, crossSectionOfVein: "185" },
          { loadCurrent: 297, crossSectionOfVein: "240" },
          { loadCurrent: 339, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "E",
        numberOfPhases: 1,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: 3,
        liczbaZyliObciazonychPradowo: 2,
        numbers: [
          { loadCurrent: 22, crossSectionOfVein: "1,5" },
          { loadCurrent: 30, crossSectionOfVein: "2,5" },
          { loadCurrent: 40, crossSectionOfVein: "4" },
          { loadCurrent: 51, crossSectionOfVein: "6" },
          { loadCurrent: 70, crossSectionOfVein: "10" },
          { loadCurrent: 94, crossSectionOfVein: "16" },
          { loadCurrent: 119, crossSectionOfVein: "25" },
          { loadCurrent: 148, crossSectionOfVein: "35" },
          { loadCurrent: 180, crossSectionOfVein: "50" },
          { loadCurrent: 232, crossSectionOfVein: "70" },
          { loadCurrent: 282, crossSectionOfVein: "95" },
          { loadCurrent: 328, crossSectionOfVein: "120" },
          { loadCurrent: 379, crossSectionOfVein: "150" },
          { loadCurrent: 434, crossSectionOfVein: "185" },
          { loadCurrent: 519, crossSectionOfVein: "240" },
          { loadCurrent: 593, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "E",
        numberOfPhases: 3,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: "4 lub 5",
        liczbaZyliObciazonychPradowo: 3,
        numbers: [
          { loadCurrent: 18.5, crossSectionOfVein: "1,5" },
          { loadCurrent: 25, crossSectionOfVein: "2,5" },
          { loadCurrent: 34, crossSectionOfVein: "4" },
          { loadCurrent: 43, crossSectionOfVein: "6" },
          { loadCurrent: 60, crossSectionOfVein: "10" },
          { loadCurrent: 80, crossSectionOfVein: "16" },
          { loadCurrent: 101, crossSectionOfVein: "25" },
          { loadCurrent: 126, crossSectionOfVein: "35" },
          { loadCurrent: 153, crossSectionOfVein: "50" },
          { loadCurrent: 196, crossSectionOfVein: "70" },
          { loadCurrent: 238, crossSectionOfVein: "95" },
          { loadCurrent: 276, crossSectionOfVein: "120" },
          { loadCurrent: 319, crossSectionOfVein: "150" },
          { loadCurrent: 364, crossSectionOfVein: "185" },
          { loadCurrent: 430, crossSectionOfVein: "240" },
          { loadCurrent: 497, crossSectionOfVein: "300" },
        ],
      },
    ],
  },
  {
    cableName: "YDYp",
    multi: [
      {
        installationType: "A1",
        numberOfPhases: 1,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: 3,
        liczbaZyliObciazonychPradowo: 2,
        numbers: [
          { loadCurrent: 14.5, crossSectionOfVein: "1,5" },
          { loadCurrent: 19.5, crossSectionOfVein: "2,5" },
          { loadCurrent: 26, crossSectionOfVein: "4" },
          { loadCurrent: 34, crossSectionOfVein: "6" },
          { loadCurrent: 46, crossSectionOfVein: "10" },
          { loadCurrent: 61, crossSectionOfVein: "16" },
          { loadCurrent: 80, crossSectionOfVein: "25" },
          { loadCurrent: 99, crossSectionOfVein: "35" },
          { loadCurrent: 119, crossSectionOfVein: "50" },
          { loadCurrent: 151, crossSectionOfVein: "70" },
          { loadCurrent: 182, crossSectionOfVein: "95" },
          { loadCurrent: 210, crossSectionOfVein: "120" },
          { loadCurrent: 240, crossSectionOfVein: "150" },
          { loadCurrent: 273, crossSectionOfVein: "185" },
          { loadCurrent: 321, crossSectionOfVein: "240" },
          { loadCurrent: 367, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "A1",
        numberOfPhases: 3,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: "4 lub 5",
        liczbaZyliObciazonychPradowo: 3,
        numbers: [
          { loadCurrent: 13.5, crossSectionOfVein: "1,5" },
          { loadCurrent: 18, crossSectionOfVein: "2,5" },
          { loadCurrent: 24, crossSectionOfVein: "4" },
          { loadCurrent: 31, crossSectionOfVein: "6" },
          { loadCurrent: 42, crossSectionOfVein: "10" },
          { loadCurrent: 56, crossSectionOfVein: "16" },
          { loadCurrent: 73, crossSectionOfVein: "25" },
          { loadCurrent: 89, crossSectionOfVein: "35" },
          { loadCurrent: 108, crossSectionOfVein: "50" },
          { loadCurrent: 136, crossSectionOfVein: "70" },
          { loadCurrent: 164, crossSectionOfVein: "95" },
          { loadCurrent: 188, crossSectionOfVein: "120" },
          { loadCurrent: 216, crossSectionOfVein: "150" },
          { loadCurrent: 245, crossSectionOfVein: "185" },
          { loadCurrent: 286, crossSectionOfVein: "240" },
          { loadCurrent: 328, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "A2",
        numberOfPhases: 1,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: 3,
        liczbaZyliObciazonychPradowo: 2,
        numbers: [
          { loadCurrent: 14, crossSectionOfVein: "1,5" },
          { loadCurrent: 18.5, crossSectionOfVein: "2,5" },
          { loadCurrent: 25, crossSectionOfVein: "4" },
          { loadCurrent: 32, crossSectionOfVein: "6" },
          { loadCurrent: 43, crossSectionOfVein: "10" },
          { loadCurrent: 57, crossSectionOfVein: "16" },
          { loadCurrent: 75, crossSectionOfVein: "25" },
          { loadCurrent: 92, crossSectionOfVein: "35" },
          { loadCurrent: 110, crossSectionOfVein: "50" },
          { loadCurrent: 139, crossSectionOfVein: "70" },
          { loadCurrent: 167, crossSectionOfVein: "95" },
          { loadCurrent: 192, crossSectionOfVein: "120" },
          { loadCurrent: 219, crossSectionOfVein: "150" },
          { loadCurrent: 248, crossSectionOfVein: "185" },
          { loadCurrent: 291, crossSectionOfVein: "240" },
          { loadCurrent: 334, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "A2",
        numberOfPhases: 3,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: "4 lub 5",
        liczbaZyliObciazonychPradowo: 3,
        numbers: [
          { loadCurrent: 13, crossSectionOfVein: "1,5" },
          { loadCurrent: 17.5, crossSectionOfVein: "2,5" },
          { loadCurrent: 23, crossSectionOfVein: "4" },
          { loadCurrent: 29, crossSectionOfVein: "6" },
          { loadCurrent: 39, crossSectionOfVein: "10" },
          { loadCurrent: 52, crossSectionOfVein: "16" },
          { loadCurrent: 68, crossSectionOfVein: "25" },
          { loadCurrent: 83, crossSectionOfVein: "35" },
          { loadCurrent: 99, crossSectionOfVein: "50" },
          { loadCurrent: 125, crossSectionOfVein: "70" },
          { loadCurrent: 150, crossSectionOfVein: "95" },
          { loadCurrent: 172, crossSectionOfVein: "120" },
          { loadCurrent: 196, crossSectionOfVein: "150" },
          { loadCurrent: 223, crossSectionOfVein: "185" },
          { loadCurrent: 261, crossSectionOfVein: "240" },
          { loadCurrent: 298, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "B2",
        numberOfPhases: 1,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: 3,
        liczbaZyliObciazonychPradowo: 2,
        numbers: [
          { loadCurrent: 16.5, crossSectionOfVein: "1,5" },
          { loadCurrent: 23, crossSectionOfVein: "2,5" },
          { loadCurrent: 30, crossSectionOfVein: "4" },
          { loadCurrent: 38, crossSectionOfVein: "6" },
          { loadCurrent: 52, crossSectionOfVein: "10" },
          { loadCurrent: 69, crossSectionOfVein: "16" },
          { loadCurrent: 90, crossSectionOfVein: "25" },
          { loadCurrent: 111, crossSectionOfVein: "35" },
          { loadCurrent: 133, crossSectionOfVein: "50" },
          { loadCurrent: 168, crossSectionOfVein: "70" },
          { loadCurrent: 201, crossSectionOfVein: "95" },
          { loadCurrent: 232, crossSectionOfVein: "120" },
          { loadCurrent: 258, crossSectionOfVein: "150" },
          { loadCurrent: 294, crossSectionOfVein: "185" },
          { loadCurrent: 344, crossSectionOfVein: "240" },
          { loadCurrent: 394, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "B2",
        numberOfPhases: 3,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: "4 lub 5",
        liczbaZyliObciazonychPradowo: 3,
        numbers: [
          { loadCurrent: 15, crossSectionOfVein: "1,5" },
          { loadCurrent: 20, crossSectionOfVein: "2,5" },
          { loadCurrent: 27, crossSectionOfVein: "4" },
          { loadCurrent: 34, crossSectionOfVein: "6" },
          { loadCurrent: 46, crossSectionOfVein: "10" },
          { loadCurrent: 62, crossSectionOfVein: "16" },
          { loadCurrent: 80, crossSectionOfVein: "25" },
          { loadCurrent: 99, crossSectionOfVein: "35" },
          { loadCurrent: 118, crossSectionOfVein: "50" },
          { loadCurrent: 149, crossSectionOfVein: "70" },
          { loadCurrent: 179, crossSectionOfVein: "95" },
          { loadCurrent: 206, crossSectionOfVein: "120" },
          { loadCurrent: 225, crossSectionOfVein: "150" },
          { loadCurrent: 255, crossSectionOfVein: "185" },
          { loadCurrent: 297, crossSectionOfVein: "240" },
          { loadCurrent: 339, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "E",
        numberOfPhases: 1,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: 3,
        liczbaZyliObciazonychPradowo: 2,
        numbers: [
          { loadCurrent: 22, crossSectionOfVein: "1,5" },
          { loadCurrent: 30, crossSectionOfVein: "2,5" },
          { loadCurrent: 40, crossSectionOfVein: "4" },
          { loadCurrent: 51, crossSectionOfVein: "6" },
          { loadCurrent: 70, crossSectionOfVein: "10" },
          { loadCurrent: 94, crossSectionOfVein: "16" },
          { loadCurrent: 119, crossSectionOfVein: "25" },
          { loadCurrent: 148, crossSectionOfVein: "35" },
          { loadCurrent: 180, crossSectionOfVein: "50" },
          { loadCurrent: 232, crossSectionOfVein: "70" },
          { loadCurrent: 282, crossSectionOfVein: "95" },
          { loadCurrent: 328, crossSectionOfVein: "120" },
          { loadCurrent: 379, crossSectionOfVein: "150" },
          { loadCurrent: 434, crossSectionOfVein: "185" },
          { loadCurrent: 519, crossSectionOfVein: "240" },
          { loadCurrent: 593, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "E",
        numberOfPhases: 3,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: "4 lub 5",
        liczbaZyliObciazonychPradowo: 3,
        numbers: [
          { loadCurrent: 18.5, crossSectionOfVein: "1,5" },
          { loadCurrent: 25, crossSectionOfVein: "2,5" },
          { loadCurrent: 34, crossSectionOfVein: "4" },
          { loadCurrent: 43, crossSectionOfVein: "6" },
          { loadCurrent: 60, crossSectionOfVein: "10" },
          { loadCurrent: 80, crossSectionOfVein: "16" },
          { loadCurrent: 101, crossSectionOfVein: "25" },
          { loadCurrent: 126, crossSectionOfVein: "35" },
          { loadCurrent: 153, crossSectionOfVein: "50" },
          { loadCurrent: 196, crossSectionOfVein: "70" },
          { loadCurrent: 238, crossSectionOfVein: "95" },
          { loadCurrent: 276, crossSectionOfVein: "120" },
          { loadCurrent: 319, crossSectionOfVein: "150" },
          { loadCurrent: 364, crossSectionOfVein: "185" },
          { loadCurrent: 430, crossSectionOfVein: "240" },
          { loadCurrent: 497, crossSectionOfVein: "300" },
        ],
      },
    ],
  },
  {
    cableName: "YKY",
    multi: [
      {
        installationType: "A1",
        numberOfPhases: 1,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: 3,
        liczbaZyliObciazonychPradowo: 2,
        numbers: [
          { loadCurrent: 14.5, crossSectionOfVein: "1,5" },
          { loadCurrent: 19.5, crossSectionOfVein: "2,5" },
          { loadCurrent: 26, crossSectionOfVein: "4" },
          { loadCurrent: 34, crossSectionOfVein: "6" },
          { loadCurrent: 46, crossSectionOfVein: "10" },
          { loadCurrent: 61, crossSectionOfVein: "16" },
          { loadCurrent: 80, crossSectionOfVein: "25" },
          { loadCurrent: 99, crossSectionOfVein: "35" },
          { loadCurrent: 119, crossSectionOfVein: "50" },
          { loadCurrent: 151, crossSectionOfVein: "70" },
          { loadCurrent: 182, crossSectionOfVein: "95" },
          { loadCurrent: 210, crossSectionOfVein: "120" },
          { loadCurrent: 240, crossSectionOfVein: "150" },
          { loadCurrent: 273, crossSectionOfVein: "185" },
          { loadCurrent: 321, crossSectionOfVein: "240" },
          { loadCurrent: 367, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "A1",
        numberOfPhases: 3,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: "4 lub 5",
        liczbaZyliObciazonychPradowo: 3,
        numbers: [
          { loadCurrent: 13.5, crossSectionOfVein: "1,5" },
          { loadCurrent: 18, crossSectionOfVein: "2,5" },
          { loadCurrent: 24, crossSectionOfVein: "4" },
          { loadCurrent: 31, crossSectionOfVein: "6" },
          { loadCurrent: 42, crossSectionOfVein: "10" },
          { loadCurrent: 56, crossSectionOfVein: "16" },
          { loadCurrent: 73, crossSectionOfVein: "25" },
          { loadCurrent: 89, crossSectionOfVein: "35" },
          { loadCurrent: 108, crossSectionOfVein: "50" },
          { loadCurrent: 136, crossSectionOfVein: "70" },
          { loadCurrent: 164, crossSectionOfVein: "95" },
          { loadCurrent: 188, crossSectionOfVein: "120" },
          { loadCurrent: 216, crossSectionOfVein: "150" },
          { loadCurrent: 245, crossSectionOfVein: "185" },
          { loadCurrent: 286, crossSectionOfVein: "240" },
          { loadCurrent: 328, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "A2",
        numberOfPhases: 1,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: 3,
        liczbaZyliObciazonychPradowo: 2,
        numbers: [
          { loadCurrent: 14, crossSectionOfVein: "1,5" },
          { loadCurrent: 18.5, crossSectionOfVein: "2,5" },
          { loadCurrent: 25, crossSectionOfVein: "4" },
          { loadCurrent: 32, crossSectionOfVein: "6" },
          { loadCurrent: 43, crossSectionOfVein: "10" },
          { loadCurrent: 57, crossSectionOfVein: "16" },
          { loadCurrent: 75, crossSectionOfVein: "25" },
          { loadCurrent: 92, crossSectionOfVein: "35" },
          { loadCurrent: 110, crossSectionOfVein: "50" },
          { loadCurrent: 139, crossSectionOfVein: "70" },
          { loadCurrent: 167, crossSectionOfVein: "95" },
          { loadCurrent: 192, crossSectionOfVein: "120" },
          { loadCurrent: 219, crossSectionOfVein: "150" },
          { loadCurrent: 248, crossSectionOfVein: "185" },
          { loadCurrent: 291, crossSectionOfVein: "240" },
          { loadCurrent: 334, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "A2",
        numberOfPhases: 3,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: "4 lub 5",
        liczbaZyliObciazonychPradowo: 3,
        numbers: [
          { loadCurrent: 13, crossSectionOfVein: "1,5" },
          { loadCurrent: 17.5, crossSectionOfVein: "2,5" },
          { loadCurrent: 23, crossSectionOfVein: "4" },
          { loadCurrent: 29, crossSectionOfVein: "6" },
          { loadCurrent: 39, crossSectionOfVein: "10" },
          { loadCurrent: 52, crossSectionOfVein: "16" },
          { loadCurrent: 68, crossSectionOfVein: "25" },
          { loadCurrent: 83, crossSectionOfVein: "35" },
          { loadCurrent: 99, crossSectionOfVein: "50" },
          { loadCurrent: 125, crossSectionOfVein: "70" },
          { loadCurrent: 150, crossSectionOfVein: "95" },
          { loadCurrent: 172, crossSectionOfVein: "120" },
          { loadCurrent: 196, crossSectionOfVein: "150" },
          { loadCurrent: 223, crossSectionOfVein: "185" },
          { loadCurrent: 261, crossSectionOfVein: "240" },
          { loadCurrent: 298, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "B2",
        numberOfPhases: 1,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: 3,
        liczbaZyliObciazonychPradowo: 2,
        numbers: [
          { loadCurrent: 16.5, crossSectionOfVein: "1,5" },
          { loadCurrent: 23, crossSectionOfVein: "2,5" },
          { loadCurrent: 30, crossSectionOfVein: "4" },
          { loadCurrent: 38, crossSectionOfVein: "6" },
          { loadCurrent: 52, crossSectionOfVein: "10" },
          { loadCurrent: 69, crossSectionOfVein: "16" },
          { loadCurrent: 90, crossSectionOfVein: "25" },
          { loadCurrent: 111, crossSectionOfVein: "35" },
          { loadCurrent: 133, crossSectionOfVein: "50" },
          { loadCurrent: 168, crossSectionOfVein: "70" },
          { loadCurrent: 201, crossSectionOfVein: "95" },
          { loadCurrent: 232, crossSectionOfVein: "120" },
          { loadCurrent: 258, crossSectionOfVein: "150" },
          { loadCurrent: 294, crossSectionOfVein: "185" },
          { loadCurrent: 344, crossSectionOfVein: "240" },
          { loadCurrent: 394, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "B2",
        numberOfPhases: 3,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: "4 lub 5",
        liczbaZyliObciazonychPradowo: 3,
        numbers: [
          { loadCurrent: 15, crossSectionOfVein: "1,5" },
          { loadCurrent: 20, crossSectionOfVein: "2,5" },
          { loadCurrent: 27, crossSectionOfVein: "4" },
          { loadCurrent: 34, crossSectionOfVein: "6" },
          { loadCurrent: 46, crossSectionOfVein: "10" },
          { loadCurrent: 62, crossSectionOfVein: "16" },
          { loadCurrent: 80, crossSectionOfVein: "25" },
          { loadCurrent: 99, crossSectionOfVein: "35" },
          { loadCurrent: 118, crossSectionOfVein: "50" },
          { loadCurrent: 149, crossSectionOfVein: "70" },
          { loadCurrent: 179, crossSectionOfVein: "95" },
          { loadCurrent: 206, crossSectionOfVein: "120" },
          { loadCurrent: 225, crossSectionOfVein: "150" },
          { loadCurrent: 255, crossSectionOfVein: "185" },
          { loadCurrent: 297, crossSectionOfVein: "240" },
          { loadCurrent: 339, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "E",
        numberOfPhases: 1,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: 3,
        liczbaZyliObciazonychPradowo: 2,
        numbers: [
          { loadCurrent: 22, crossSectionOfVein: "1,5" },
          { loadCurrent: 30, crossSectionOfVein: "2,5" },
          { loadCurrent: 40, crossSectionOfVein: "4" },
          { loadCurrent: 51, crossSectionOfVein: "6" },
          { loadCurrent: 70, crossSectionOfVein: "10" },
          { loadCurrent: 94, crossSectionOfVein: "16" },
          { loadCurrent: 119, crossSectionOfVein: "25" },
          { loadCurrent: 148, crossSectionOfVein: "35" },
          { loadCurrent: 180, crossSectionOfVein: "50" },
          { loadCurrent: 232, crossSectionOfVein: "70" },
          { loadCurrent: 282, crossSectionOfVein: "95" },
          { loadCurrent: 328, crossSectionOfVein: "120" },
          { loadCurrent: 379, crossSectionOfVein: "150" },
          { loadCurrent: 434, crossSectionOfVein: "185" },
          { loadCurrent: 519, crossSectionOfVein: "240" },
          { loadCurrent: 593, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "E",
        numberOfPhases: 3,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: "4 lub 5",
        liczbaZyliObciazonychPradowo: 3,
        numbers: [
          { loadCurrent: 18.5, crossSectionOfVein: "1,5" },
          { loadCurrent: 25, crossSectionOfVein: "2,5" },
          { loadCurrent: 34, crossSectionOfVein: "4" },
          { loadCurrent: 43, crossSectionOfVein: "6" },
          { loadCurrent: 60, crossSectionOfVein: "10" },
          { loadCurrent: 80, crossSectionOfVein: "16" },
          { loadCurrent: 101, crossSectionOfVein: "25" },
          { loadCurrent: 126, crossSectionOfVein: "35" },
          { loadCurrent: 153, crossSectionOfVein: "50" },
          { loadCurrent: 196, crossSectionOfVein: "70" },
          { loadCurrent: 238, crossSectionOfVein: "95" },
          { loadCurrent: 276, crossSectionOfVein: "120" },
          { loadCurrent: 319, crossSectionOfVein: "150" },
          { loadCurrent: 364, crossSectionOfVein: "185" },
          { loadCurrent: 430, crossSectionOfVein: "240" },
          { loadCurrent: 497, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "D2",
        numberOfPhases: 1,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: 3,
        liczbaZyliObciazonychPradowo: 2,
        numbers: [
          { loadCurrent: 33, crossSectionOfVein: "1,5" },
          { loadCurrent: 42, crossSectionOfVein: "2,5" },
          { loadCurrent: 57, crossSectionOfVein: "4" },
          { loadCurrent: 72, crossSectionOfVein: "6" },
          { loadCurrent: 96, crossSectionOfVein: "10" },
          { loadCurrent: 124, crossSectionOfVein: "16" },
          { loadCurrent: 165, crossSectionOfVein: "25" },
          { loadCurrent: 198, crossSectionOfVein: "35" },
          { loadCurrent: 234, crossSectionOfVein: "50" },
          { loadCurrent: 288, crossSectionOfVein: "70" },
          { loadCurrent: 345, crossSectionOfVein: "95" },
          { loadCurrent: 391, crossSectionOfVein: "120" },
          { loadCurrent: 439, crossSectionOfVein: "150" },
          { loadCurrent: 496, crossSectionOfVein: "185" },
          { loadCurrent: 573, crossSectionOfVein: "240" },
          { loadCurrent: 640, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "D2",
        numberOfPhases: 3,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: "4 lub 5",
        liczbaZyliObciazonychPradowo: 3,
        numbers: [
          { loadCurrent: 28, crossSectionOfVein: "1,5" },
          { loadCurrent: 36, crossSectionOfVein: "2,5" },
          { loadCurrent: 49, crossSectionOfVein: "4" },
          { loadCurrent: 61, crossSectionOfVein: "6" },
          { loadCurrent: 81, crossSectionOfVein: "10" },
          { loadCurrent: 105, crossSectionOfVein: "16" },
          { loadCurrent: 138, crossSectionOfVein: "25" },
          { loadCurrent: 165, crossSectionOfVein: "35" },
          { loadCurrent: 195, crossSectionOfVein: "50" },
          { loadCurrent: 243, crossSectionOfVein: "70" },
          { loadCurrent: 289, crossSectionOfVein: "95" },
          { loadCurrent: 330, crossSectionOfVein: "120" },
          { loadCurrent: 369, crossSectionOfVein: "150" },
          { loadCurrent: 417, crossSectionOfVein: "185" },
          { loadCurrent: 480, crossSectionOfVein: "240" },
          { loadCurrent: 538, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "D1",
        numberOfPhases: 1,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: 3,
        liczbaZyliObciazonychPradowo: 2,
        numbers: [
          { loadCurrent: 25, crossSectionOfVein: "1,5" },
          { loadCurrent: 34, crossSectionOfVein: "2,5" },
          { loadCurrent: 43, crossSectionOfVein: "4" },
          { loadCurrent: 54, crossSectionOfVein: "6" },
          { loadCurrent: 70, crossSectionOfVein: "10" },
          { loadCurrent: 92, crossSectionOfVein: "16" },
          { loadCurrent: 116, crossSectionOfVein: "25" },
          { loadCurrent: 140, crossSectionOfVein: "35" },
          { loadCurrent: 165, crossSectionOfVein: "50" },
          { loadCurrent: 204, crossSectionOfVein: "70" },
          { loadCurrent: 240, crossSectionOfVein: "95" },
          { loadCurrent: 272, crossSectionOfVein: "120" },
          { loadCurrent: 307, crossSectionOfVein: "150" },
          { loadCurrent: 344, crossSectionOfVein: "185" },
          { loadCurrent: 396, crossSectionOfVein: "240" },
          { loadCurrent: 447, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "D1",
        numberOfPhases: 3,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: "4 lub 5",
        liczbaZyliObciazonychPradowo: 3,
        numbers: [
          { loadCurrent: 21, crossSectionOfVein: "1,5" },
          { loadCurrent: 28, crossSectionOfVein: "2,5" },
          { loadCurrent: 35, crossSectionOfVein: "4" },
          { loadCurrent: 44, crossSectionOfVein: "6" },
          { loadCurrent: 59, crossSectionOfVein: "10" },
          { loadCurrent: 75, crossSectionOfVein: "16" },
          { loadCurrent: 96, crossSectionOfVein: "25" },
          { loadCurrent: 115, crossSectionOfVein: "35" },
          { loadCurrent: 136, crossSectionOfVein: "50" },
          { loadCurrent: 168, crossSectionOfVein: "70" },
          { loadCurrent: 199, crossSectionOfVein: "95" },
          { loadCurrent: 226, crossSectionOfVein: "120" },
          { loadCurrent: 256, crossSectionOfVein: "150" },
          { loadCurrent: 286, crossSectionOfVein: "185" },
          { loadCurrent: 330, crossSectionOfVein: "240" },
          { loadCurrent: 372, crossSectionOfVein: "300" },
        ],
      },
    ],
    one: [
      {
        installationType: "A1",
        numberOfPhases: 3,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: 1,
        liczbaZyliObciazonychPradowo: 3,
        numbers: [
          { loadCurrent: 13.5, crossSectionOfVein: "1,5" },
          { loadCurrent: 18, crossSectionOfVein: "2,5" },
          { loadCurrent: 24, crossSectionOfVein: "4" },
          { loadCurrent: 31, crossSectionOfVein: "6" },
          { loadCurrent: 42, crossSectionOfVein: "10" },
          { loadCurrent: 56, crossSectionOfVein: "16" },
          { loadCurrent: 73, crossSectionOfVein: "25" },
          { loadCurrent: 89, crossSectionOfVein: "35" },
          { loadCurrent: 108, crossSectionOfVein: "50" },
          { loadCurrent: 136, crossSectionOfVein: "70" },
          { loadCurrent: 164, crossSectionOfVein: "95" },
          { loadCurrent: 188, crossSectionOfVein: "120" },
          { loadCurrent: 216, crossSectionOfVein: "150" },
          { loadCurrent: 245, crossSectionOfVein: "185" },
          { loadCurrent: 286, crossSectionOfVein: "240" },
          { loadCurrent: 328, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "B1",
        numberOfPhases: 3,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: 1,
        liczbaZyliObciazonychPradowo: 3,
        numbers: [
          { loadCurrent: 15.5, crossSectionOfVein: "1,5" },
          { loadCurrent: 21, crossSectionOfVein: "2,5" },
          { loadCurrent: 28, crossSectionOfVein: "4" },
          { loadCurrent: 36, crossSectionOfVein: "6" },
          { loadCurrent: 50, crossSectionOfVein: "10" },
          { loadCurrent: 68, crossSectionOfVein: "16" },
          { loadCurrent: 89, crossSectionOfVein: "25" },
          { loadCurrent: 110, crossSectionOfVein: "35" },
          { loadCurrent: 134, crossSectionOfVein: "50" },
          { loadCurrent: 171, crossSectionOfVein: "70" },
          { loadCurrent: 207, crossSectionOfVein: "95" },
          { loadCurrent: 239, crossSectionOfVein: "120" },
          { loadCurrent: 262, crossSectionOfVein: "150" },
          { loadCurrent: 296, crossSectionOfVein: "185" },
          { loadCurrent: 346, crossSectionOfVein: "240" },
          { loadCurrent: 394, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "F",
        numberOfPhases: 3,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: 1,
        liczbaZyliObciazonychPradowo: 3,
        numbers: [
          { loadCurrent: null, crossSectionOfVein: "4" },
          { loadCurrent: null, crossSectionOfVein: "6" },
          { loadCurrent: null, crossSectionOfVein: "10" },
          { loadCurrent: null, crossSectionOfVein: "16" },
          { loadCurrent: null, crossSectionOfVein: "1,5" },
          { loadCurrent: null, crossSectionOfVein: "2,5" },
          { loadCurrent: 110, crossSectionOfVein: "25" },
          { loadCurrent: 137, crossSectionOfVein: "35" },
          { loadCurrent: 167, crossSectionOfVein: "50" },
          { loadCurrent: 216, crossSectionOfVein: "70" },
          { loadCurrent: 264, crossSectionOfVein: "95" },
          { loadCurrent: 308, crossSectionOfVein: "120" },
          { loadCurrent: 356, crossSectionOfVein: "150" },
          { loadCurrent: 409, crossSectionOfVein: "185" },
          { loadCurrent: 485, crossSectionOfVein: "240" },
          { loadCurrent: 561, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "D2",
        numberOfPhases: 3,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: 1,
        liczbaZyliObciazonychPradowo: 3,
        numbers: [
          { loadCurrent: 28, crossSectionOfVein: "1,5" },
          { loadCurrent: 36, crossSectionOfVein: "2,5" },
          { loadCurrent: 49, crossSectionOfVein: "4" },
          { loadCurrent: 61, crossSectionOfVein: "6" },
          { loadCurrent: 81, crossSectionOfVein: "10" },
          { loadCurrent: 105, crossSectionOfVein: "16" },
          { loadCurrent: 138, crossSectionOfVein: "25" },
          { loadCurrent: 165, crossSectionOfVein: "35" },
          { loadCurrent: 195, crossSectionOfVein: "50" },
          { loadCurrent: 243, crossSectionOfVein: "70" },
          { loadCurrent: 289, crossSectionOfVein: "95" },
          { loadCurrent: 330, crossSectionOfVein: "120" },
          { loadCurrent: 369, crossSectionOfVein: "150" },
          { loadCurrent: 417, crossSectionOfVein: "185" },
          { loadCurrent: 480, crossSectionOfVein: "240" },
          { loadCurrent: 538, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "D1",
        numberOfPhases: 3,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: 1,
        liczbaZyliObciazonychPradowo: 3,
        numbers: [
          { loadCurrent: 21, crossSectionOfVein: "1,5" },
          { loadCurrent: 28, crossSectionOfVein: "2,5" },
          { loadCurrent: 35, crossSectionOfVein: "4" },
          { loadCurrent: 44, crossSectionOfVein: "6" },
          { loadCurrent: 59, crossSectionOfVein: "10" },
          { loadCurrent: 75, crossSectionOfVein: "16" },
          { loadCurrent: 96, crossSectionOfVein: "25" },
          { loadCurrent: 115, crossSectionOfVein: "35" },
          { loadCurrent: 136, crossSectionOfVein: "50" },
          { loadCurrent: 168, crossSectionOfVein: "70" },
          { loadCurrent: 199, crossSectionOfVein: "95" },
          { loadCurrent: 226, crossSectionOfVein: "120" },
          { loadCurrent: 256, crossSectionOfVein: "150" },
          { loadCurrent: 286, crossSectionOfVein: "185" },
          { loadCurrent: 330, crossSectionOfVein: "240" },
          { loadCurrent: 372, crossSectionOfVein: "300" },
        ],
      },
    ],
  },
  {
    cableName: "YKXS",
    multi: [
      {
        installationType: "A1",
        numberOfPhases: 1,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: 3,
        liczbaZyliObciazonychPradowo: 2,
        numbers: [
          { loadCurrent: 19, crossSectionOfVein: "1,5" },
          { loadCurrent: 26, crossSectionOfVein: "2,5" },
          { loadCurrent: 35, crossSectionOfVein: "4" },
          { loadCurrent: 45, crossSectionOfVein: "6" },
          { loadCurrent: 61, crossSectionOfVein: "10" },
          { loadCurrent: 81, crossSectionOfVein: "16" },
          { loadCurrent: 106, crossSectionOfVein: "25" },
          { loadCurrent: 131, crossSectionOfVein: "35" },
          { loadCurrent: 158, crossSectionOfVein: "50" },
          { loadCurrent: 200, crossSectionOfVein: "70" },
          { loadCurrent: 241, crossSectionOfVein: "95" },
          { loadCurrent: 278, crossSectionOfVein: "120" },
          { loadCurrent: 318, crossSectionOfVein: "150" },
          { loadCurrent: 362, crossSectionOfVein: "185" },
          { loadCurrent: 424, crossSectionOfVein: "240" },
          { loadCurrent: 486, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "A1",
        numberOfPhases: 3,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: "4 lub 5",
        liczbaZyliObciazonychPradowo: 3,
        numbers: [
          { loadCurrent: 17, crossSectionOfVein: "1,5" },
          { loadCurrent: 23, crossSectionOfVein: "2,5" },
          { loadCurrent: 31, crossSectionOfVein: "4" },
          { loadCurrent: 40, crossSectionOfVein: "6" },
          { loadCurrent: 54, crossSectionOfVein: "10" },
          { loadCurrent: 73, crossSectionOfVein: "16" },
          { loadCurrent: 95, crossSectionOfVein: "25" },
          { loadCurrent: 117, crossSectionOfVein: "35" },
          { loadCurrent: 141, crossSectionOfVein: "50" },
          { loadCurrent: 179, crossSectionOfVein: "70" },
          { loadCurrent: 216, crossSectionOfVein: "95" },
          { loadCurrent: 249, crossSectionOfVein: "120" },
          { loadCurrent: 285, crossSectionOfVein: "150" },
          { loadCurrent: 324, crossSectionOfVein: "185" },
          { loadCurrent: 380, crossSectionOfVein: "240" },
          { loadCurrent: 435, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "A2",
        numberOfPhases: 1,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: 3,
        liczbaZyliObciazonychPradowo: 2,
        numbers: [
          { loadCurrent: 18.5, crossSectionOfVein: "1,5" },
          { loadCurrent: 25, crossSectionOfVein: "2,5" },
          { loadCurrent: 33, crossSectionOfVein: "4" },
          { loadCurrent: 42, crossSectionOfVein: "6" },
          { loadCurrent: 57, crossSectionOfVein: "10" },
          { loadCurrent: 76, crossSectionOfVein: "16" },
          { loadCurrent: 99, crossSectionOfVein: "25" },
          { loadCurrent: 121, crossSectionOfVein: "35" },
          { loadCurrent: 145, crossSectionOfVein: "50" },
          { loadCurrent: 183, crossSectionOfVein: "70" },
          { loadCurrent: 220, crossSectionOfVein: "95" },
          { loadCurrent: 253, crossSectionOfVein: "120" },
          { loadCurrent: 290, crossSectionOfVein: "150" },
          { loadCurrent: 329, crossSectionOfVein: "185" },
          { loadCurrent: 386, crossSectionOfVein: "240" },
          { loadCurrent: 442, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "A2",
        numberOfPhases: 3,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: "4 lub 5",
        liczbaZyliObciazonychPradowo: 3,
        numbers: [
          { loadCurrent: 16.5, crossSectionOfVein: "1,5" },
          { loadCurrent: 22, crossSectionOfVein: "2,5" },
          { loadCurrent: 30, crossSectionOfVein: "4" },
          { loadCurrent: 38, crossSectionOfVein: "6" },
          { loadCurrent: 51, crossSectionOfVein: "10" },
          { loadCurrent: 68, crossSectionOfVein: "16" },
          { loadCurrent: 89, crossSectionOfVein: "25" },
          { loadCurrent: 109, crossSectionOfVein: "35" },
          { loadCurrent: 130, crossSectionOfVein: "50" },
          { loadCurrent: 164, crossSectionOfVein: "70" },
          { loadCurrent: 197, crossSectionOfVein: "95" },
          { loadCurrent: 227, crossSectionOfVein: "120" },
          { loadCurrent: 259, crossSectionOfVein: "150" },
          { loadCurrent: 295, crossSectionOfVein: "185" },
          { loadCurrent: 346, crossSectionOfVein: "240" },
          { loadCurrent: 396, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "B2",
        numberOfPhases: 1,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: 3,
        liczbaZyliObciazonychPradowo: 2,
        numbers: [
          { loadCurrent: 22, crossSectionOfVein: "1,5" },
          { loadCurrent: 30, crossSectionOfVein: "2,5" },
          { loadCurrent: 40, crossSectionOfVein: "4" },
          { loadCurrent: 51, crossSectionOfVein: "6" },
          { loadCurrent: 69, crossSectionOfVein: "10" },
          { loadCurrent: 91, crossSectionOfVein: "16" },
          { loadCurrent: 119, crossSectionOfVein: "25" },
          { loadCurrent: 146, crossSectionOfVein: "35" },
          { loadCurrent: 175, crossSectionOfVein: "50" },
          { loadCurrent: 221, crossSectionOfVein: "70" },
          { loadCurrent: 265, crossSectionOfVein: "95" },
          { loadCurrent: 305, crossSectionOfVein: "120" },
          { loadCurrent: 334, crossSectionOfVein: "150" },
          { loadCurrent: 384, crossSectionOfVein: "185" },
          { loadCurrent: 459, crossSectionOfVein: "240" },
          { loadCurrent: 532, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "B2",
        numberOfPhases: 3,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: "4 lub 5",
        liczbaZyliObciazonychPradowo: 3,
        numbers: [
          { loadCurrent: 19.5, crossSectionOfVein: "1,5" },
          { loadCurrent: 26, crossSectionOfVein: "2,5" },
          { loadCurrent: 35, crossSectionOfVein: "4" },
          { loadCurrent: 44, crossSectionOfVein: "6" },
          { loadCurrent: 60, crossSectionOfVein: "10" },
          { loadCurrent: 80, crossSectionOfVein: "16" },
          { loadCurrent: 105, crossSectionOfVein: "25" },
          { loadCurrent: 128, crossSectionOfVein: "35" },
          { loadCurrent: 154, crossSectionOfVein: "50" },
          { loadCurrent: 194, crossSectionOfVein: "70" },
          { loadCurrent: 233, crossSectionOfVein: "95" },
          { loadCurrent: 268, crossSectionOfVein: "120" },
          { loadCurrent: 300, crossSectionOfVein: "150" },
          { loadCurrent: 340, crossSectionOfVein: "185" },
          { loadCurrent: 398, crossSectionOfVein: "240" },
          { loadCurrent: 455, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "E",
        numberOfPhases: 1,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: 3,
        liczbaZyliObciazonychPradowo: 2,
        numbers: [
          { loadCurrent: 26, crossSectionOfVein: "1,5" },
          { loadCurrent: 36, crossSectionOfVein: "2,5" },
          { loadCurrent: 49, crossSectionOfVein: "4" },
          { loadCurrent: 63, crossSectionOfVein: "6" },
          { loadCurrent: 86, crossSectionOfVein: "10" },
          { loadCurrent: 115, crossSectionOfVein: "16" },
          { loadCurrent: 149, crossSectionOfVein: "25" },
          { loadCurrent: 185, crossSectionOfVein: "35" },
          { loadCurrent: 225, crossSectionOfVein: "50" },
          { loadCurrent: 289, crossSectionOfVein: "70" },
          { loadCurrent: 352, crossSectionOfVein: "95" },
          { loadCurrent: 410, crossSectionOfVein: "120" },
          { loadCurrent: 473, crossSectionOfVein: "150" },
          { loadCurrent: 542, crossSectionOfVein: "185" },
          { loadCurrent: 641, crossSectionOfVein: "240" },
          { loadCurrent: 741, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "E",
        numberOfPhases: 3,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: "4 lub 5",
        liczbaZyliObciazonychPradowo: 3,
        numbers: [
          { loadCurrent: 23, crossSectionOfVein: "1,5" },
          { loadCurrent: 32, crossSectionOfVein: "2,5" },
          { loadCurrent: 42, crossSectionOfVein: "4" },
          { loadCurrent: 54, crossSectionOfVein: "6" },
          { loadCurrent: 75, crossSectionOfVein: "10" },
          { loadCurrent: 100, crossSectionOfVein: "16" },
          { loadCurrent: 127, crossSectionOfVein: "25" },
          { loadCurrent: 158, crossSectionOfVein: "35" },
          { loadCurrent: 192, crossSectionOfVein: "50" },
          { loadCurrent: 246, crossSectionOfVein: "70" },
          { loadCurrent: 298, crossSectionOfVein: "95" },
          { loadCurrent: 346, crossSectionOfVein: "120" },
          { loadCurrent: 399, crossSectionOfVein: "150" },
          { loadCurrent: 456, crossSectionOfVein: "185" },
          { loadCurrent: 538, crossSectionOfVein: "240" },
          { loadCurrent: 621, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "D2",
        numberOfPhases: 1,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: 3,
        liczbaZyliObciazonychPradowo: 2,
        numbers: [
          { loadCurrent: 40, crossSectionOfVein: "1,5" },
          { loadCurrent: 52, crossSectionOfVein: "2,5" },
          { loadCurrent: 69, crossSectionOfVein: "4" },
          { loadCurrent: 87, crossSectionOfVein: "6" },
          { loadCurrent: 115, crossSectionOfVein: "10" },
          { loadCurrent: 150, crossSectionOfVein: "16" },
          { loadCurrent: 193, crossSectionOfVein: "25" },
          { loadCurrent: 232, crossSectionOfVein: "35" },
          { loadCurrent: 274, crossSectionOfVein: "50" },
          { loadCurrent: 337, crossSectionOfVein: "70" },
          { loadCurrent: 405, crossSectionOfVein: "95" },
          { loadCurrent: 459, crossSectionOfVein: "120" },
          { loadCurrent: 514, crossSectionOfVein: "150" },
          { loadCurrent: 580, crossSectionOfVein: "185" },
          { loadCurrent: 672, crossSectionOfVein: "240" },
          { loadCurrent: 753, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "D2",
        numberOfPhases: 3,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: "4 lub 5",
        liczbaZyliObciazonychPradowo: 3,
        numbers: [
          { loadCurrent: 34, crossSectionOfVein: "1,5" },
          { loadCurrent: 45, crossSectionOfVein: "2,5" },
          { loadCurrent: 58, crossSectionOfVein: "4" },
          { loadCurrent: 73, crossSectionOfVein: "6" },
          { loadCurrent: 97, crossSectionOfVein: "10" },
          { loadCurrent: 126, crossSectionOfVein: "16" },
          { loadCurrent: 160, crossSectionOfVein: "25" },
          { loadCurrent: 193, crossSectionOfVein: "35" },
          { loadCurrent: 229, crossSectionOfVein: "50" },
          { loadCurrent: 282, crossSectionOfVein: "70" },
          { loadCurrent: 339, crossSectionOfVein: "95" },
          { loadCurrent: 385, crossSectionOfVein: "120" },
          { loadCurrent: 430, crossSectionOfVein: "150" },
          { loadCurrent: 486, crossSectionOfVein: "185" },
          { loadCurrent: 562, crossSectionOfVein: "240" },
          { loadCurrent: 628, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "D1",
        numberOfPhases: 1,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: 3,
        liczbaZyliObciazonychPradowo: 2,
        numbers: [
          { loadCurrent: 29, crossSectionOfVein: "1,5" },
          { loadCurrent: 38, crossSectionOfVein: "2,5" },
          { loadCurrent: 50, crossSectionOfVein: "4" },
          { loadCurrent: 62, crossSectionOfVein: "6" },
          { loadCurrent: 83, crossSectionOfVein: "10" },
          { loadCurrent: 107, crossSectionOfVein: "16" },
          { loadCurrent: 136, crossSectionOfVein: "25" },
          { loadCurrent: 164, crossSectionOfVein: "35" },
          { loadCurrent: 193, crossSectionOfVein: "50" },
          { loadCurrent: 239, crossSectionOfVein: "70" },
          { loadCurrent: 282, crossSectionOfVein: "95" },
          { loadCurrent: 319, crossSectionOfVein: "120" },
          { loadCurrent: 361, crossSectionOfVein: "150" },
          { loadCurrent: 404, crossSectionOfVein: "185" },
          { loadCurrent: 466, crossSectionOfVein: "240" },
          { loadCurrent: 526, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "D1",
        numberOfPhases: 3,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: "4 lub 5",
        liczbaZyliObciazonychPradowo: 3,
        numbers: [
          { loadCurrent: 24, crossSectionOfVein: "1,5" },
          { loadCurrent: 33, crossSectionOfVein: "2,5" },
          { loadCurrent: 42, crossSectionOfVein: "4" },
          { loadCurrent: 51, crossSectionOfVein: "6" },
          { loadCurrent: 68, crossSectionOfVein: "10" },
          { loadCurrent: 88, crossSectionOfVein: "16" },
          { loadCurrent: 113, crossSectionOfVein: "25" },
          { loadCurrent: 135, crossSectionOfVein: "35" },
          { loadCurrent: 159, crossSectionOfVein: "50" },
          { loadCurrent: 197, crossSectionOfVein: "70" },
          { loadCurrent: 232, crossSectionOfVein: "95" },
          { loadCurrent: 263, crossSectionOfVein: "120" },
          { loadCurrent: 296, crossSectionOfVein: "150" },
          { loadCurrent: 331, crossSectionOfVein: "185" },
          { loadCurrent: 382, crossSectionOfVein: "240" },
          { loadCurrent: 430, crossSectionOfVein: "300" },
        ],
      },
    ],
    one: [
      {
        installationType: "A1",
        numberOfPhases: 3,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: 1,
        liczbaZyliObciazonychPradowo: 3,
        numbers: [
          { loadCurrent: 17, crossSectionOfVein: "1,5" },
          { loadCurrent: 23, crossSectionOfVein: "2,5" },
          { loadCurrent: 31, crossSectionOfVein: "4" },
          { loadCurrent: 40, crossSectionOfVein: "6" },
          { loadCurrent: 54, crossSectionOfVein: "10" },
          { loadCurrent: 73, crossSectionOfVein: "16" },
          { loadCurrent: 95, crossSectionOfVein: "25" },
          { loadCurrent: 117, crossSectionOfVein: "35" },
          { loadCurrent: 141, crossSectionOfVein: "50" },
          { loadCurrent: 179, crossSectionOfVein: "70" },
          { loadCurrent: 216, crossSectionOfVein: "95" },
          { loadCurrent: 249, crossSectionOfVein: "120" },
          { loadCurrent: 285, crossSectionOfVein: "150" },
          { loadCurrent: 324, crossSectionOfVein: "185" },
          { loadCurrent: 380, crossSectionOfVein: "240" },
          { loadCurrent: 435, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "B1",
        numberOfPhases: 3,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: 1,
        liczbaZyliObciazonychPradowo: 3,
        numbers: [
          { loadCurrent: 20, crossSectionOfVein: "1,5" },
          { loadCurrent: 28, crossSectionOfVein: "2,5" },
          { loadCurrent: 37, crossSectionOfVein: "4" },
          { loadCurrent: 48, crossSectionOfVein: "6" },
          { loadCurrent: 66, crossSectionOfVein: "10" },
          { loadCurrent: 88, crossSectionOfVein: "16" },
          { loadCurrent: 117, crossSectionOfVein: "25" },
          { loadCurrent: 144, crossSectionOfVein: "35" },
          { loadCurrent: 175, crossSectionOfVein: "50" },
          { loadCurrent: 222, crossSectionOfVein: "70" },
          { loadCurrent: 269, crossSectionOfVein: "95" },
          { loadCurrent: 312, crossSectionOfVein: "120" },
          { loadCurrent: 342, crossSectionOfVein: "150" },
          { loadCurrent: 384, crossSectionOfVein: "185" },
          { loadCurrent: 450, crossSectionOfVein: "240" },
          { loadCurrent: 514, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "F",
        numberOfPhases: 3,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: 1,
        liczbaZyliObciazonychPradowo: 3,
        numbers: [
          { loadCurrent: null, crossSectionOfVein: "4" },
          { loadCurrent: null, crossSectionOfVein: "6" },
          { loadCurrent: null, crossSectionOfVein: "10" },
          { loadCurrent: null, crossSectionOfVein: "16" },
          { loadCurrent: null, crossSectionOfVein: "1,5" },
          { loadCurrent: null, crossSectionOfVein: "2,5" },
          { loadCurrent: 135, crossSectionOfVein: "25" },
          { loadCurrent: 169, crossSectionOfVein: "35" },
          { loadCurrent: 207, crossSectionOfVein: "50" },
          { loadCurrent: 268, crossSectionOfVein: "70" },
          { loadCurrent: 328, crossSectionOfVein: "95" },
          { loadCurrent: 383, crossSectionOfVein: "120" },
          { loadCurrent: 444, crossSectionOfVein: "150" },
          { loadCurrent: 510, crossSectionOfVein: "185" },
          { loadCurrent: 607, crossSectionOfVein: "240" },
          { loadCurrent: 703, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "D2",
        numberOfPhases: 3,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: 1,
        liczbaZyliObciazonychPradowo: 3,
        numbers: [
          { loadCurrent: 34, crossSectionOfVein: "1,5" },
          { loadCurrent: 45, crossSectionOfVein: "2,5" },
          { loadCurrent: 58, crossSectionOfVein: "4" },
          { loadCurrent: 73, crossSectionOfVein: "6" },
          { loadCurrent: 97, crossSectionOfVein: "10" },
          { loadCurrent: 126, crossSectionOfVein: "16" },
          { loadCurrent: 160, crossSectionOfVein: "25" },
          { loadCurrent: 193, crossSectionOfVein: "35" },
          { loadCurrent: 229, crossSectionOfVein: "50" },
          { loadCurrent: 282, crossSectionOfVein: "70" },
          { loadCurrent: 339, crossSectionOfVein: "95" },
          { loadCurrent: 385, crossSectionOfVein: "120" },
          { loadCurrent: 430, crossSectionOfVein: "150" },
          { loadCurrent: 486, crossSectionOfVein: "185" },
          { loadCurrent: 562, crossSectionOfVein: "240" },
          { loadCurrent: 628, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "D1",
        numberOfPhases: 3,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: 1,
        liczbaZyliObciazonychPradowo: 3,
        numbers: [
          { loadCurrent: 24, crossSectionOfVein: "1,5" },
          { loadCurrent: 33, crossSectionOfVein: "2,5" },
          { loadCurrent: 42, crossSectionOfVein: "4" },
          { loadCurrent: 51, crossSectionOfVein: "6" },
          { loadCurrent: 68, crossSectionOfVein: "10" },
          { loadCurrent: 88, crossSectionOfVein: "16" },
          { loadCurrent: 113, crossSectionOfVein: "25" },
          { loadCurrent: 135, crossSectionOfVein: "35" },
          { loadCurrent: 159, crossSectionOfVein: "50" },
          { loadCurrent: 197, crossSectionOfVein: "70" },
          { loadCurrent: 232, crossSectionOfVein: "95" },
          { loadCurrent: 263, crossSectionOfVein: "120" },
          { loadCurrent: 296, crossSectionOfVein: "150" },
          { loadCurrent: 331, crossSectionOfVein: "185" },
          { loadCurrent: 382, crossSectionOfVein: "240" },
          { loadCurrent: 430, crossSectionOfVein: "300" },
        ],
      },
    ],
  },
  {
    cableName: "YAKXS",
    multi: [
      {
        installationType: "A1",
        numberOfPhases: 1,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: 3,
        liczbaZyliObciazonychPradowo: 2,
        numbers: [
          { loadCurrent: null, crossSectionOfVein: "1,5" },
          { loadCurrent: 20, crossSectionOfVein: "2,5" },
          { loadCurrent: 27, crossSectionOfVein: "4" },
          { loadCurrent: 35, crossSectionOfVein: "6" },
          { loadCurrent: 48, crossSectionOfVein: "10" },
          { loadCurrent: 64, crossSectionOfVein: "16" },
          { loadCurrent: 84, crossSectionOfVein: "25" },
          { loadCurrent: 103, crossSectionOfVein: "35" },
          { loadCurrent: 125, crossSectionOfVein: "50" },
          { loadCurrent: 158, crossSectionOfVein: "70" },
          { loadCurrent: 191, crossSectionOfVein: "95" },
          { loadCurrent: 220, crossSectionOfVein: "120" },
          { loadCurrent: 253, crossSectionOfVein: "150" },
          { loadCurrent: 288, crossSectionOfVein: "185" },
          { loadCurrent: 338, crossSectionOfVein: "240" },
          { loadCurrent: 387, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "A1",
        numberOfPhases: 3,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: "4 lub 5",
        liczbaZyliObciazonychPradowo: 3,
        numbers: [
          { loadCurrent: null, crossSectionOfVein: "1,5" },
          { loadCurrent: 19, crossSectionOfVein: "2,5" },
          { loadCurrent: 25, crossSectionOfVein: "4" },
          { loadCurrent: 32, crossSectionOfVein: "6" },
          { loadCurrent: 44, crossSectionOfVein: "10" },
          { loadCurrent: 58, crossSectionOfVein: "16" },
          { loadCurrent: 76, crossSectionOfVein: "25" },
          { loadCurrent: 94, crossSectionOfVein: "35" },
          { loadCurrent: 113, crossSectionOfVein: "50" },
          { loadCurrent: 142, crossSectionOfVein: "70" },
          { loadCurrent: 171, crossSectionOfVein: "95" },
          { loadCurrent: 197, crossSectionOfVein: "120" },
          { loadCurrent: 226, crossSectionOfVein: "150" },
          { loadCurrent: 256, crossSectionOfVein: "185" },
          { loadCurrent: 300, crossSectionOfVein: "240" },
          { loadCurrent: 344, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "A2",
        numberOfPhases: 1,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: 3,
        liczbaZyliObciazonychPradowo: 2,
        numbers: [
          { loadCurrent: null, crossSectionOfVein: "1,5" },
          { loadCurrent: 19.5, crossSectionOfVein: "2,5" },
          { loadCurrent: 26, crossSectionOfVein: "4" },
          { loadCurrent: 33, crossSectionOfVein: "6" },
          { loadCurrent: 45, crossSectionOfVein: "10" },
          { loadCurrent: 60, crossSectionOfVein: "16" },
          { loadCurrent: 78, crossSectionOfVein: "25" },
          { loadCurrent: 96, crossSectionOfVein: "35" },
          { loadCurrent: 115, crossSectionOfVein: "50" },
          { loadCurrent: 145, crossSectionOfVein: "70" },
          { loadCurrent: 175, crossSectionOfVein: "95" },
          { loadCurrent: 201, crossSectionOfVein: "120" },
          { loadCurrent: 230, crossSectionOfVein: "150" },
          { loadCurrent: 262, crossSectionOfVein: "185" },
          { loadCurrent: 307, crossSectionOfVein: "240" },
          { loadCurrent: 352, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "A2",
        numberOfPhases: 3,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: "4 lub 5",
        liczbaZyliObciazonychPradowo: 3,
        numbers: [
          { loadCurrent: null, crossSectionOfVein: "1,5" },
          { loadCurrent: 18, crossSectionOfVein: "2,5" },
          { loadCurrent: 24, crossSectionOfVein: "4" },
          { loadCurrent: 31, crossSectionOfVein: "6" },
          { loadCurrent: 41, crossSectionOfVein: "10" },
          { loadCurrent: 55, crossSectionOfVein: "16" },
          { loadCurrent: 71, crossSectionOfVein: "25" },
          { loadCurrent: 87, crossSectionOfVein: "35" },
          { loadCurrent: 104, crossSectionOfVein: "50" },
          { loadCurrent: 131, crossSectionOfVein: "70" },
          { loadCurrent: 157, crossSectionOfVein: "95" },
          { loadCurrent: 180, crossSectionOfVein: "120" },
          { loadCurrent: 206, crossSectionOfVein: "150" },
          { loadCurrent: 233, crossSectionOfVein: "185" },
          { loadCurrent: 273, crossSectionOfVein: "240" },
          { loadCurrent: 313, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "B2",
        numberOfPhases: 1,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: 3,
        liczbaZyliObciazonychPradowo: 2,
        numbers: [
          { loadCurrent: null, crossSectionOfVein: "1,5" },
          { loadCurrent: 23, crossSectionOfVein: "2,5" },
          { loadCurrent: 31, crossSectionOfVein: "4" },
          { loadCurrent: 40, crossSectionOfVein: "6" },
          { loadCurrent: 54, crossSectionOfVein: "10" },
          { loadCurrent: 72, crossSectionOfVein: "16" },
          { loadCurrent: 94, crossSectionOfVein: "25" },
          { loadCurrent: 115, crossSectionOfVein: "35" },
          { loadCurrent: 138, crossSectionOfVein: "50" },
          { loadCurrent: 175, crossSectionOfVein: "70" },
          { loadCurrent: 210, crossSectionOfVein: "95" },
          { loadCurrent: 242, crossSectionOfVein: "120" },
          { loadCurrent: 261, crossSectionOfVein: "150" },
          { loadCurrent: 300, crossSectionOfVein: "185" },
          { loadCurrent: 358, crossSectionOfVein: "240" },
          { loadCurrent: 415, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "B2",
        numberOfPhases: 3,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: "4 lub 5",
        liczbaZyliObciazonychPradowo: 3,
        numbers: [
          { loadCurrent: null, crossSectionOfVein: "1,5" },
          { loadCurrent: 21, crossSectionOfVein: "2,5" },
          { loadCurrent: 28, crossSectionOfVein: "4" },
          { loadCurrent: 35, crossSectionOfVein: "6" },
          { loadCurrent: 48, crossSectionOfVein: "10" },
          { loadCurrent: 64, crossSectionOfVein: "16" },
          { loadCurrent: 84, crossSectionOfVein: "25" },
          { loadCurrent: 103, crossSectionOfVein: "35" },
          { loadCurrent: 124, crossSectionOfVein: "50" },
          { loadCurrent: 156, crossSectionOfVein: "70" },
          { loadCurrent: 188, crossSectionOfVein: "95" },
          { loadCurrent: 216, crossSectionOfVein: "120" },
          { loadCurrent: 240, crossSectionOfVein: "150" },
          { loadCurrent: 272, crossSectionOfVein: "185" },
          { loadCurrent: 318, crossSectionOfVein: "240" },
          { loadCurrent: 364, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "E",
        numberOfPhases: 1,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: 3,
        liczbaZyliObciazonychPradowo: 2,
        numbers: [
          { loadCurrent: null, crossSectionOfVein: "1,5" },
          { loadCurrent: 28, crossSectionOfVein: "2,5" },
          { loadCurrent: 38, crossSectionOfVein: "4" },
          { loadCurrent: 49, crossSectionOfVein: "6" },
          { loadCurrent: 67, crossSectionOfVein: "10" },
          { loadCurrent: 91, crossSectionOfVein: "16" },
          { loadCurrent: 108, crossSectionOfVein: "25" },
          { loadCurrent: 135, crossSectionOfVein: "35" },
          { loadCurrent: 164, crossSectionOfVein: "50" },
          { loadCurrent: 211, crossSectionOfVein: "70" },
          { loadCurrent: 257, crossSectionOfVein: "95" },
          { loadCurrent: 300, crossSectionOfVein: "120" },
          { loadCurrent: 346, crossSectionOfVein: "150" },
          { loadCurrent: 397, crossSectionOfVein: "185" },
          { loadCurrent: 470, crossSectionOfVein: "240" },
          { loadCurrent: 543, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "E",
        numberOfPhases: 3,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: "4 lub 5",
        liczbaZyliObciazonychPradowo: 3,
        numbers: [
          { loadCurrent: null, crossSectionOfVein: "1,5" },
          { loadCurrent: 24, crossSectionOfVein: "2,5" },
          { loadCurrent: 32, crossSectionOfVein: "4" },
          { loadCurrent: 42, crossSectionOfVein: "6" },
          { loadCurrent: 58, crossSectionOfVein: "10" },
          { loadCurrent: 77, crossSectionOfVein: "16" },
          { loadCurrent: 97, crossSectionOfVein: "25" },
          { loadCurrent: 120, crossSectionOfVein: "35" },
          { loadCurrent: 146, crossSectionOfVein: "50" },
          { loadCurrent: 187, crossSectionOfVein: "70" },
          { loadCurrent: 227, crossSectionOfVein: "95" },
          { loadCurrent: 263, crossSectionOfVein: "120" },
          { loadCurrent: 304, crossSectionOfVein: "150" },
          { loadCurrent: 347, crossSectionOfVein: "185" },
          { loadCurrent: 409, crossSectionOfVein: "240" },
          { loadCurrent: 471, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "D2",
        numberOfPhases: 1,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: 3,
        liczbaZyliObciazonychPradowo: 2,
        numbers: [
          { loadCurrent: null, crossSectionOfVein: "4" },
          { loadCurrent: null, crossSectionOfVein: "6" },
          { loadCurrent: null, crossSectionOfVein: "10" },
          { loadCurrent: null, crossSectionOfVein: "1,5" },
          { loadCurrent: null, crossSectionOfVein: "2,5" },
          { loadCurrent: 114, crossSectionOfVein: "16" },
          { loadCurrent: 147, crossSectionOfVein: "25" },
          { loadCurrent: 175, crossSectionOfVein: "35" },
          { loadCurrent: 208, crossSectionOfVein: "50" },
          { loadCurrent: 255, crossSectionOfVein: "70" },
          { loadCurrent: 306, crossSectionOfVein: "95" },
          { loadCurrent: 349, crossSectionOfVein: "120" },
          { loadCurrent: 391, crossSectionOfVein: "150" },
          { loadCurrent: 444, crossSectionOfVein: "185" },
          { loadCurrent: 514, crossSectionOfVein: "240" },
          { loadCurrent: 579, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "D2",
        numberOfPhases: 3,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: "4 lub 5",
        liczbaZyliObciazonychPradowo: 3,
        numbers: [
          { loadCurrent: null, crossSectionOfVein: "4" },
          { loadCurrent: null, crossSectionOfVein: "6" },
          { loadCurrent: null, crossSectionOfVein: "10" },
          { loadCurrent: null, crossSectionOfVein: "1,5" },
          { loadCurrent: null, crossSectionOfVein: "2,5" },
          { loadCurrent: 96, crossSectionOfVein: "16" },
          { loadCurrent: 123, crossSectionOfVein: "25" },
          { loadCurrent: 147, crossSectionOfVein: "35" },
          { loadCurrent: 175, crossSectionOfVein: "50" },
          { loadCurrent: 216, crossSectionOfVein: "70" },
          { loadCurrent: 258, crossSectionOfVein: "95" },
          { loadCurrent: 295, crossSectionOfVein: "120" },
          { loadCurrent: 330, crossSectionOfVein: "150" },
          { loadCurrent: 375, crossSectionOfVein: "185" },
          { loadCurrent: 435, crossSectionOfVein: "240" },
          { loadCurrent: 489, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "D1",
        numberOfPhases: 1,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: 3,
        liczbaZyliObciazonychPradowo: 2,
        numbers: [
          { loadCurrent: null, crossSectionOfVein: "1,5" },
          { loadCurrent: 30, crossSectionOfVein: "2,5" },
          { loadCurrent: 38, crossSectionOfVein: "4" },
          { loadCurrent: 49, crossSectionOfVein: "6" },
          { loadCurrent: 64, crossSectionOfVein: "10" },
          { loadCurrent: 83, crossSectionOfVein: "16" },
          { loadCurrent: 106, crossSectionOfVein: "25" },
          { loadCurrent: 127, crossSectionOfVein: "35" },
          { loadCurrent: 151, crossSectionOfVein: "50" },
          { loadCurrent: 186, crossSectionOfVein: "70" },
          { loadCurrent: 219, crossSectionOfVein: "95" },
          { loadCurrent: 248, crossSectionOfVein: "120" },
          { loadCurrent: 280, crossSectionOfVein: "150" },
          { loadCurrent: 315, crossSectionOfVein: "185" },
          { loadCurrent: 362, crossSectionOfVein: "240" },
          { loadCurrent: 408, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "D1",
        numberOfPhases: 3,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: "4 lub 5",
        liczbaZyliObciazonychPradowo: 3,
        numbers: [
          { loadCurrent: null, crossSectionOfVein: "1,5" },
          { loadCurrent: 25, crossSectionOfVein: "2,5" },
          { loadCurrent: 33, crossSectionOfVein: "4" },
          { loadCurrent: 41, crossSectionOfVein: "6" },
          { loadCurrent: 54, crossSectionOfVein: "10" },
          { loadCurrent: 69, crossSectionOfVein: "16" },
          { loadCurrent: 88, crossSectionOfVein: "25" },
          { loadCurrent: 106, crossSectionOfVein: "35" },
          { loadCurrent: 125, crossSectionOfVein: "50" },
          { loadCurrent: 153, crossSectionOfVein: "70" },
          { loadCurrent: 181, crossSectionOfVein: "95" },
          { loadCurrent: 205, crossSectionOfVein: "120" },
          { loadCurrent: 232, crossSectionOfVein: "150" },
          { loadCurrent: 259, crossSectionOfVein: "185" },
          { loadCurrent: 298, crossSectionOfVein: "240" },
          { loadCurrent: 337, crossSectionOfVein: "300" },
        ],
      },
    ],
    one: [
      {
        installationType: "A1",
        numberOfPhases: 3,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: 1,
        liczbaZyliObciazonychPradowo: 3,
        numbers: [
          { loadCurrent: null, crossSectionOfVein: "1,5" },
          { loadCurrent: 19, crossSectionOfVein: "2,5" },
          { loadCurrent: 25, crossSectionOfVein: "4" },
          { loadCurrent: 32, crossSectionOfVein: "6" },
          { loadCurrent: 44, crossSectionOfVein: "10" },
          { loadCurrent: 58, crossSectionOfVein: "16" },
          { loadCurrent: 76, crossSectionOfVein: "25" },
          { loadCurrent: 94, crossSectionOfVein: "35" },
          { loadCurrent: 113, crossSectionOfVein: "50" },
          { loadCurrent: 142, crossSectionOfVein: "70" },
          { loadCurrent: 171, crossSectionOfVein: "95" },
          { loadCurrent: 197, crossSectionOfVein: "120" },
          { loadCurrent: 226, crossSectionOfVein: "150" },
          { loadCurrent: 256, crossSectionOfVein: "185" },
          { loadCurrent: 300, crossSectionOfVein: "240" },
          { loadCurrent: 344, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "B1",
        numberOfPhases: 3,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: 1,
        liczbaZyliObciazonychPradowo: 3,
        numbers: [
          { loadCurrent: null, crossSectionOfVein: "1,5" },
          { loadCurrent: 22, crossSectionOfVein: "2,5" },
          { loadCurrent: 29, crossSectionOfVein: "4" },
          { loadCurrent: 38, crossSectionOfVein: "6" },
          { loadCurrent: 52, crossSectionOfVein: "10" },
          { loadCurrent: 71, crossSectionOfVein: "16" },
          { loadCurrent: 93, crossSectionOfVein: "25" },
          { loadCurrent: 116, crossSectionOfVein: "35" },
          { loadCurrent: 140, crossSectionOfVein: "50" },
          { loadCurrent: 179, crossSectionOfVein: "70" },
          { loadCurrent: 217, crossSectionOfVein: "95" },
          { loadCurrent: 251, crossSectionOfVein: "120" },
          { loadCurrent: 267, crossSectionOfVein: "150" },
          { loadCurrent: 300, crossSectionOfVein: "185" },
          { loadCurrent: 351, crossSectionOfVein: "240" },
          { loadCurrent: 402, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "F",
        numberOfPhases: 3,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: 1,
        liczbaZyliObciazonychPradowo: 3,
        numbers: [
          { loadCurrent: null, crossSectionOfVein: "4" },
          { loadCurrent: null, crossSectionOfVein: "6" },
          { loadCurrent: null, crossSectionOfVein: "10" },
          { loadCurrent: null, crossSectionOfVein: "16" },
          { loadCurrent: null, crossSectionOfVein: "1,5" },
          { loadCurrent: null, crossSectionOfVein: "2,5" },
          { loadCurrent: 103, crossSectionOfVein: "25" },
          { loadCurrent: 129, crossSectionOfVein: "35" },
          { loadCurrent: 159, crossSectionOfVein: "50" },
          { loadCurrent: 206, crossSectionOfVein: "70" },
          { loadCurrent: 253, crossSectionOfVein: "95" },
          { loadCurrent: 296, crossSectionOfVein: "120" },
          { loadCurrent: 343, crossSectionOfVein: "150" },
          { loadCurrent: 395, crossSectionOfVein: "185" },
          { loadCurrent: 471, crossSectionOfVein: "240" },
          { loadCurrent: 547, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "D2",
        numberOfPhases: 3,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: 1,
        liczbaZyliObciazonychPradowo: 3,
        numbers: [
          { loadCurrent: null, crossSectionOfVein: "4" },
          { loadCurrent: null, crossSectionOfVein: "6" },
          { loadCurrent: null, crossSectionOfVein: "10" },
          { loadCurrent: null, crossSectionOfVein: "1,5" },
          { loadCurrent: null, crossSectionOfVein: "2,5" },
          { loadCurrent: 96, crossSectionOfVein: "16" },
          { loadCurrent: 123, crossSectionOfVein: "25" },
          { loadCurrent: 147, crossSectionOfVein: "35" },
          { loadCurrent: 175, crossSectionOfVein: "50" },
          { loadCurrent: 216, crossSectionOfVein: "70" },
          { loadCurrent: 258, crossSectionOfVein: "95" },
          { loadCurrent: 295, crossSectionOfVein: "120" },
          { loadCurrent: 330, crossSectionOfVein: "150" },
          { loadCurrent: 375, crossSectionOfVein: "185" },
          { loadCurrent: 435, crossSectionOfVein: "240" },
          { loadCurrent: 489, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "D1",
        numberOfPhases: 3,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: 1,
        liczbaZyliObciazonychPradowo: 3,
        numbers: [
          { loadCurrent: null, crossSectionOfVein: "1,5" },
          { loadCurrent: 25, crossSectionOfVein: "2,5" },
          { loadCurrent: 33, crossSectionOfVein: "4" },
          { loadCurrent: 41, crossSectionOfVein: "6" },
          { loadCurrent: 54, crossSectionOfVein: "10" },
          { loadCurrent: 69, crossSectionOfVein: "16" },
          { loadCurrent: 88, crossSectionOfVein: "25" },
          { loadCurrent: 106, crossSectionOfVein: "35" },
          { loadCurrent: 125, crossSectionOfVein: "50" },
          { loadCurrent: 153, crossSectionOfVein: "70" },
          { loadCurrent: 181, crossSectionOfVein: "95" },
          { loadCurrent: 205, crossSectionOfVein: "120" },
          { loadCurrent: 232, crossSectionOfVein: "150" },
          { loadCurrent: 259, crossSectionOfVein: "185" },
          { loadCurrent: 298, crossSectionOfVein: "240" },
          { loadCurrent: 337, crossSectionOfVein: "300" },
        ],
      },
    ],
  },
  {
    cableName: "N2XH",
    multi: [
      {
        installationType: "A1",
        numberOfPhases: 1,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: 3,
        liczbaZyliObciazonychPradowo: 2,
        numbers: [
          { loadCurrent: 19, crossSectionOfVein: "1,5" },
          { loadCurrent: 26, crossSectionOfVein: "2,5" },
          { loadCurrent: 35, crossSectionOfVein: "4" },
          { loadCurrent: 45, crossSectionOfVein: "6" },
          { loadCurrent: 61, crossSectionOfVein: "10" },
          { loadCurrent: 81, crossSectionOfVein: "16" },
          { loadCurrent: 106, crossSectionOfVein: "25" },
          { loadCurrent: 131, crossSectionOfVein: "35" },
          { loadCurrent: 158, crossSectionOfVein: "50" },
          { loadCurrent: 200, crossSectionOfVein: "70" },
          { loadCurrent: 241, crossSectionOfVein: "95" },
          { loadCurrent: 278, crossSectionOfVein: "120" },
          { loadCurrent: 318, crossSectionOfVein: "150" },
          { loadCurrent: 362, crossSectionOfVein: "185" },
          { loadCurrent: 424, crossSectionOfVein: "240" },
          { loadCurrent: 486, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "A1",
        numberOfPhases: 3,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: "4 lub 5",
        liczbaZyliObciazonychPradowo: 3,
        numbers: [
          { loadCurrent: 17, crossSectionOfVein: "1,5" },
          { loadCurrent: 23, crossSectionOfVein: "2,5" },
          { loadCurrent: 31, crossSectionOfVein: "4" },
          { loadCurrent: 40, crossSectionOfVein: "6" },
          { loadCurrent: 54, crossSectionOfVein: "10" },
          { loadCurrent: 73, crossSectionOfVein: "16" },
          { loadCurrent: 95, crossSectionOfVein: "25" },
          { loadCurrent: 117, crossSectionOfVein: "35" },
          { loadCurrent: 141, crossSectionOfVein: "50" },
          { loadCurrent: 179, crossSectionOfVein: "70" },
          { loadCurrent: 216, crossSectionOfVein: "95" },
          { loadCurrent: 249, crossSectionOfVein: "120" },
          { loadCurrent: 285, crossSectionOfVein: "150" },
          { loadCurrent: 324, crossSectionOfVein: "185" },
          { loadCurrent: 380, crossSectionOfVein: "240" },
          { loadCurrent: 435, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "A2",
        numberOfPhases: 1,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: 3,
        liczbaZyliObciazonychPradowo: 2,
        numbers: [
          { loadCurrent: 18.5, crossSectionOfVein: "1,5" },
          { loadCurrent: 25, crossSectionOfVein: "2,5" },
          { loadCurrent: 33, crossSectionOfVein: "4" },
          { loadCurrent: 42, crossSectionOfVein: "6" },
          { loadCurrent: 57, crossSectionOfVein: "10" },
          { loadCurrent: 76, crossSectionOfVein: "16" },
          { loadCurrent: 99, crossSectionOfVein: "25" },
          { loadCurrent: 121, crossSectionOfVein: "35" },
          { loadCurrent: 145, crossSectionOfVein: "50" },
          { loadCurrent: 183, crossSectionOfVein: "70" },
          { loadCurrent: 220, crossSectionOfVein: "95" },
          { loadCurrent: 253, crossSectionOfVein: "120" },
          { loadCurrent: 290, crossSectionOfVein: "150" },
          { loadCurrent: 329, crossSectionOfVein: "185" },
          { loadCurrent: 386, crossSectionOfVein: "240" },
          { loadCurrent: 442, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "A2",
        numberOfPhases: 3,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: "4 lub 5",
        liczbaZyliObciazonychPradowo: 3,
        numbers: [
          { loadCurrent: 16.5, crossSectionOfVein: "1,5" },
          { loadCurrent: 22, crossSectionOfVein: "2,5" },
          { loadCurrent: 30, crossSectionOfVein: "4" },
          { loadCurrent: 38, crossSectionOfVein: "6" },
          { loadCurrent: 51, crossSectionOfVein: "10" },
          { loadCurrent: 68, crossSectionOfVein: "16" },
          { loadCurrent: 89, crossSectionOfVein: "25" },
          { loadCurrent: 109, crossSectionOfVein: "35" },
          { loadCurrent: 130, crossSectionOfVein: "50" },
          { loadCurrent: 164, crossSectionOfVein: "70" },
          { loadCurrent: 197, crossSectionOfVein: "95" },
          { loadCurrent: 227, crossSectionOfVein: "120" },
          { loadCurrent: 259, crossSectionOfVein: "150" },
          { loadCurrent: 295, crossSectionOfVein: "185" },
          { loadCurrent: 346, crossSectionOfVein: "240" },
          { loadCurrent: 396, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "B2",
        numberOfPhases: 1,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: 3,
        liczbaZyliObciazonychPradowo: 2,
        numbers: [
          { loadCurrent: 22, crossSectionOfVein: "1,5" },
          { loadCurrent: 30, crossSectionOfVein: "2,5" },
          { loadCurrent: 40, crossSectionOfVein: "4" },
          { loadCurrent: 51, crossSectionOfVein: "6" },
          { loadCurrent: 69, crossSectionOfVein: "10" },
          { loadCurrent: 91, crossSectionOfVein: "16" },
          { loadCurrent: 119, crossSectionOfVein: "25" },
          { loadCurrent: 146, crossSectionOfVein: "35" },
          { loadCurrent: 175, crossSectionOfVein: "50" },
          { loadCurrent: 221, crossSectionOfVein: "70" },
          { loadCurrent: 265, crossSectionOfVein: "95" },
          { loadCurrent: 305, crossSectionOfVein: "120" },
          { loadCurrent: 334, crossSectionOfVein: "150" },
          { loadCurrent: 384, crossSectionOfVein: "185" },
          { loadCurrent: 459, crossSectionOfVein: "240" },
          { loadCurrent: 532, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "B2",
        numberOfPhases: 3,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: "4 lub 5",
        liczbaZyliObciazonychPradowo: 3,
        numbers: [
          { loadCurrent: 19.5, crossSectionOfVein: "1,5" },
          { loadCurrent: 26, crossSectionOfVein: "2,5" },
          { loadCurrent: 35, crossSectionOfVein: "4" },
          { loadCurrent: 44, crossSectionOfVein: "6" },
          { loadCurrent: 60, crossSectionOfVein: "10" },
          { loadCurrent: 80, crossSectionOfVein: "16" },
          { loadCurrent: 105, crossSectionOfVein: "25" },
          { loadCurrent: 128, crossSectionOfVein: "35" },
          { loadCurrent: 154, crossSectionOfVein: "50" },
          { loadCurrent: 194, crossSectionOfVein: "70" },
          { loadCurrent: 233, crossSectionOfVein: "95" },
          { loadCurrent: 268, crossSectionOfVein: "120" },
          { loadCurrent: 300, crossSectionOfVein: "150" },
          { loadCurrent: 340, crossSectionOfVein: "185" },
          { loadCurrent: 398, crossSectionOfVein: "240" },
          { loadCurrent: 455, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "E",
        numberOfPhases: 1,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: 3,
        liczbaZyliObciazonychPradowo: 2,
        numbers: [
          { loadCurrent: 26, crossSectionOfVein: "1,5" },
          { loadCurrent: 36, crossSectionOfVein: "2,5" },
          { loadCurrent: 49, crossSectionOfVein: "4" },
          { loadCurrent: 63, crossSectionOfVein: "6" },
          { loadCurrent: 86, crossSectionOfVein: "10" },
          { loadCurrent: 115, crossSectionOfVein: "16" },
          { loadCurrent: 149, crossSectionOfVein: "25" },
          { loadCurrent: 185, crossSectionOfVein: "35" },
          { loadCurrent: 225, crossSectionOfVein: "50" },
          { loadCurrent: 289, crossSectionOfVein: "70" },
          { loadCurrent: 352, crossSectionOfVein: "95" },
          { loadCurrent: 410, crossSectionOfVein: "120" },
          { loadCurrent: 473, crossSectionOfVein: "150" },
          { loadCurrent: 542, crossSectionOfVein: "185" },
          { loadCurrent: 641, crossSectionOfVein: "240" },
          { loadCurrent: 741, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "E",
        numberOfPhases: 3,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: "4 lub 5",
        liczbaZyliObciazonychPradowo: 3,
        numbers: [
          { loadCurrent: 24, crossSectionOfVein: "1,5" },
          { loadCurrent: 32, crossSectionOfVein: "2,5" },
          { loadCurrent: 42, crossSectionOfVein: "4" },
          { loadCurrent: 53, crossSectionOfVein: "6" },
          { loadCurrent: 74, crossSectionOfVein: "10" },
          { loadCurrent: 98, crossSectionOfVein: "16" },
          { loadCurrent: 133, crossSectionOfVein: "25" },
          { loadCurrent: 162, crossSectionOfVein: "35" },
          { loadCurrent: 197, crossSectionOfVein: "50" },
          { loadCurrent: 250, crossSectionOfVein: "70" },
          { loadCurrent: 308, crossSectionOfVein: "95" },
          { loadCurrent: 359, crossSectionOfVein: "120" },
          { loadCurrent: 412, crossSectionOfVein: "150" },
          { loadCurrent: 475, crossSectionOfVein: "185" },
          { loadCurrent: 564, crossSectionOfVein: "240" },
          { loadCurrent: 649, crossSectionOfVein: "300" },
        ],
      },
    ],
    one: [
      {
        installationType: "A1",
        numberOfPhases: 3,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: 1,
        liczbaZyliObciazonychPradowo: 3,
        numbers: [
          { loadCurrent: 17, crossSectionOfVein: "1,5" },
          { loadCurrent: 23, crossSectionOfVein: "2,5" },
          { loadCurrent: 31, crossSectionOfVein: "4" },
          { loadCurrent: 40, crossSectionOfVein: "6" },
          { loadCurrent: 54, crossSectionOfVein: "10" },
          { loadCurrent: 73, crossSectionOfVein: "16" },
          { loadCurrent: 95, crossSectionOfVein: "25" },
          { loadCurrent: 117, crossSectionOfVein: "35" },
          { loadCurrent: 141, crossSectionOfVein: "50" },
          { loadCurrent: 179, crossSectionOfVein: "70" },
          { loadCurrent: 216, crossSectionOfVein: "95" },
          { loadCurrent: 249, crossSectionOfVein: "120" },
          { loadCurrent: 285, crossSectionOfVein: "150" },
          { loadCurrent: 324, crossSectionOfVein: "185" },
          { loadCurrent: 380, crossSectionOfVein: "240" },
          { loadCurrent: 435, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "B1",
        numberOfPhases: 3,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: 1,
        liczbaZyliObciazonychPradowo: 3,
        numbers: [
          { loadCurrent: 20, crossSectionOfVein: "1,5" },
          { loadCurrent: 28, crossSectionOfVein: "2,5" },
          { loadCurrent: 37, crossSectionOfVein: "4" },
          { loadCurrent: 48, crossSectionOfVein: "6" },
          { loadCurrent: 66, crossSectionOfVein: "10" },
          { loadCurrent: 88, crossSectionOfVein: "16" },
          { loadCurrent: 117, crossSectionOfVein: "25" },
          { loadCurrent: 144, crossSectionOfVein: "35" },
          { loadCurrent: 175, crossSectionOfVein: "50" },
          { loadCurrent: 222, crossSectionOfVein: "70" },
          { loadCurrent: 269, crossSectionOfVein: "95" },
          { loadCurrent: 312, crossSectionOfVein: "120" },
          { loadCurrent: 342, crossSectionOfVein: "150" },
          { loadCurrent: 384, crossSectionOfVein: "185" },
          { loadCurrent: 450, crossSectionOfVein: "240" },
          { loadCurrent: 514, crossSectionOfVein: "300" },
        ],
      },
      {
        installationType: "F",
        numberOfPhases: 3,
        veinCrossing: "obciążalność prądowa",
        liczbaZyli: 1,
        liczbaZyliObciazonychPradowo: 3,
        numbers: [
          { loadCurrent: 26, crossSectionOfVein: "1,5" },
          { loadCurrent: 34, crossSectionOfVein: "2,5" },
          { loadCurrent: 44, crossSectionOfVein: "4" },
          { loadCurrent: 56, crossSectionOfVein: "6" },
          { loadCurrent: 77, crossSectionOfVein: "10" },
          { loadCurrent: 102, crossSectionOfVein: "16" },
          { loadCurrent: 138, crossSectionOfVein: "25" },
          { loadCurrent: 170, crossSectionOfVein: "35" },
          { loadCurrent: 207, crossSectionOfVein: "50" },
          { loadCurrent: 263, crossSectionOfVein: "70" },
          { loadCurrent: 325, crossSectionOfVein: "95" },
          { loadCurrent: 380, crossSectionOfVein: "120" },
          { loadCurrent: 437, crossSectionOfVein: "150" },
          { loadCurrent: 507, crossSectionOfVein: "185" },
          { loadCurrent: 604, crossSectionOfVein: "240" },
          { loadCurrent: 697, crossSectionOfVein: "300" },
        ],
      },
    ],
  },
];
